services:
  - type: web
    name: ramankur-enterprises
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
